name: Run PHPUnit Tests with Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [8.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, xml, json, libxml

      - name: Install dependencies
        run: composer install --working-dir=PrivateBin-main

      - name: Run PHPUnit with Code Coverage
        run: |
          cd PrivateBin-main
          ./vendor/bin/phpunit --coverage-cobertura=coverage_cobertura.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: PrivateBin-main/coverage_cobertura.xml

      - name: Check coverage report file
        run: cat PrivateBin-main/coverage_cobertura.xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: PrivateBin-main/coverage_cobertura.xml
          badge: true
          format: markdown
          output: both

      - name: Generate and Display Code Coverage Summary in Table
        run: |
          echo "### Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Covered | Total | Percentage |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|---------|-------|------------|" >> $GITHUB_STEP_SUMMARY
          coverage=$(./vendor/bin/phpunit --coverage-text --colors=never | grep -E "(Lines|Methods|Classes)")
          lines=$(echo "$coverage" | grep "Lines" | awk '{print $2 " | " $4 " | " $6 " | " $8}')
          methods=$(echo "$coverage" | grep "Methods" | awk '{print $2 " | " $4 " | " $6 " | " $8}')
          classes=$(echo "$coverage" | grep "Classes" | awk '{print $2 " | " $4 " | " $6 " | " $8}')
          echo "| Lines | $lines |" >> $GITHUB_STEP_SUMMARY
          echo "| Methods | $methods |" >> $GITHUB_STEP_SUMMARY
          echo "| Classes | $classes |" >> $GITHUB_STEP_SUMMARY


