name: Run PHPUnit Tests with Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [8.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, xml, json, libxml

      - name: Install dependencies
        run: composer install --working-dir=PrivateBin-main

      - name: Run PHPUnit with Code Coverage
        run: |
          cd PrivateBin-main
          ./vendor/bin/phpunit --coverage-cobertura=coverage_cobertura.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: PrivateBin-main/coverage_cobertura.xml

      - name: Check coverage report file
        run: cat PrivateBin-main/coverage_cobertura.xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: PrivateBin-main/coverage_cobertura.xml
          badge: true
          format: markdown
          output: both

      - name: Generate and Display Code Coverage Summary
        run: |
          cd PrivateBin-main
          echo "### Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          ./vendor/bin/phpunit --coverage-text --colors=never >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_URL }}
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.MDP }}
          server-dir: 'www/'
          exclude: 'vendor/'
          

